// Generated by scripts/generate_workspace_config.py - do not edit by hand
#ifndef WORKSPACE_CONFIG_GENERATED_H
#define WORKSPACE_CONFIG_GENERATED_H
#define ARM_GCC_PATH "C:/ST/STM32CubeCLT_1.19.0/GNU-tools-for-STM32/bin/arm-none-eabi-gcc.exe"
#define ARM_GPP_PATH "C:/ST/STM32CubeCLT_1.19.0/GNU-tools-for-STM32/bin/arm-none-eabi-g++.exe"
#define CMAKE_TOOLCHAIN_FILE_PATH "cmake/gcc-arm-none-eabi.cmake"
#endif // WORKSPACE_CONFIG_GENERATED_H
