name: Generate Docs

on:
  workflow_dispatch: {}

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run generation script
        run: |
          python scripts/generate_docs.py --commit
